#!/usr/bin/env bash

## This file is run for codespaces.

if ! [ -x "$(command -v fish)" ]; then
  if [ -x "$(command -v apt)" ]; then
    echo "››› installing fish"
    sudo apt update && sudo apt-get install -y fish
  fi
fi

temp=$( realpath "$0"  )
DIR=$( dirname "$temp" )
echo "››› installing .dotfiles from $DIR"

ln -sf "$DIR/git/.gitconfig" ~/.gitconfig
ln -sf "$DIR"/git/.gitconfig.codespaces ~/.gitconfig.codespaces
ln -sf "$DIR"/zsh/.zshrc ~/.zshrc
ln -sf "$DIR"/zsh/.zshenv ~/.zshenv

## There may already be a ~/.config/ directory, so we symlink everything under it.
mkdir -p ~/.config/fish
ln -sf "$DIR"/fish/config.fish ~/.config/fish/config.fish
ln -sf "$DIR"/fish/functions ~/.config/fish/functions
